### ISSUE TITLE
Codecov is not giving us a gating check for CI

### ISSUE THREAD

**Issue by ehashman** [RackSec/cloudpassage-lib#16]
We encountered this issue on another repo as well. Not sure what's going on, all the settings look right on our end. Suspect it's a codecov problem.

**Comment by reaperhulk** [comment]
The issue here is that the bot we use to perform actions with codecov (racksec-bot) needs write privileges to a repo to be able to send status API updates (this is a requirement that I've lamented to github support a few times so hopefully some day there will be more granular permissions for this). I just added this repo to racksec-bot's privilege list so it should be okay now.

**Comment by ehashman** [comment]
Looks like @reaperhulk fixed this but the issue never got closed. Yay!
